---
services:
  kopia:
    image: kopia/kopia:latest
    hostname: kopia-backup
    container_name: kopia
    restart: always
    ports:
      - 51515:51515
    # Setup the server that provides the web gui
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=${USER}
      - --server-password=${KOPIA_PASSWORD}
      - --password=${KOPIA_PASSWORD}
    env_file:
      - .env
    volumes:
      # Mount local folders needed by kopia
      - /opt/kopia/config/dir:/app/config
      - /opt/kopia/cache/dir:/app/cache
      - /opt/kopia/logs/dir:/app/logs
      - /backup:/opt/kopia-docker

      # Mount local folders to snapshot
      - /opt/:/data:ro
      # Mount repository location
      - /media/externalHdd/niflheim/backup:/repository
      # Mount path for browsing mounted snaphots
      - /mnt/kopia:/tmp:shared
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
