services:
  storyteller-api:
    image: registry.gitlab.com/smoores/storyteller/api:latest
    volumes:
      # - /tmp/Storyteller:/data:rw
      - /media/externalHdd/niflheim/Storyteller:/data:rw
    environment:
      # CORS
      - STORYTELLER_ALLOWED_ORIGINS=https://storyteller.lan.niflheim.online
    # ports:
    #   - "8000:8000"

  storyteller-web:
    image: registry.gitlab.com/smoores/storyteller/web:latest
    environment:
      - STORYTELLER_API_HOST=http://storyteller-api:8000
      # - PUBLIC_STORYTELLER_API_HOST=https://
    ports:
      - "8001:8001"
