# Connect to tailscale and Login (when not using the auth key)
# docker-compose exec tailscale tailscale up

# Connect with exit node enabled and subnets advertised
# docker exec tailscale tailscale up --advertise-exit-node --advertise-routes=192.168.1.0/24
# docker compose exec tailscale tailscale up

# Get status
# docker exec tailscale tailscale status
---
services:
  tailscale:
    container_name: tailscale
    hostname: niflheim # Used by MagicDNS
    image: tailscale/tailscale:stable
    volumes:
      - /opt/tailscale-vpn:/var/lib # State data will be stored in this directory
      - /dev/net/tun:/dev/net/tun # Required for tailscale to work
    cap_add:
      - net_admin
      - sys_module
    command: tailscaled
    privileged: true
    restart: always
    network_mode: host

    # FIXME: tailscale doesn't seem to recognise env variables, https://hub.docker.com/r/tailscale/tailscale
    env_file:
      - .env
    labels:
      - 'kopia_backup'
      # Disable automatic watchtower updates to prevent braking changes
      # - 'com.centurylinklabs.watchtower.enable=true'