---
services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    hostname: firefox
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=2002
      - PGID=2003
      - TZ=Asia/Kolkata
    volumes:
      - /opt/firefox/config:/config
    ports:
      - 3222:3000
    shm_size: "1gb"
    restart: unless-stopped
