version: "3"

services:

  wireguard:
    image: linuxserver/wireguard:v1.0.20210914-ls7 #Use this image, latest seems to have issues
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
    ports:
      - "5000:5000"
      - "51820:51820/udp"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.wg-http.entrypoints=http"
      - "traefik.http.routers.wg-http.middlewares=redir-https"
      - "traefik.http.routers.wg-http.rule=Host(`wg.linuxpad.blog`)"
      - "traefik.http.routers.wg-http.service=noop@internal"
      - "traefik.http.routers.wg-https.entrypoints=https"
      - "traefik.http.routers.wg-https.tls=true"
      - "traefik.http.routers.wg-https.middlewares=gzip"
      - "traefik.http.routers.wg-https.rule=Host(`wg.linuxpad.blog`)"
      - "traefik.http.services.wg-backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.wg-backend.loadbalancer.server.port=5000"
      - "traefik.http.routers.wg-https.middlewares=authelia@docker"




  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=password
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - ./config:/etc/wireguard

networks:
  traefik:
    external: true
